### ISSUE TITLE
Code assumes json format for CycloneDX SBOMs

### ISSUE THREAD

**Issue by cyberbliss** [eBay/sbom-scorecard#16]
Hi,

The code for specifying the CDX decoder assumes that the SBOM will be in json format:
In cdx_report.go:
`decoder := cdx.NewBOMDecoder(f, cdx.BOMFileFormatJSON)`

As a consequence any XML format CycloneDX SBOMs get marked as invalid specs. This seems misleading to me.

**Comment by jspeed-meyers** [comment]
I think that adding XML support would be a nice additional feature.

Additionally, it would be useful to have the tool report--in the meantime before XML parsing functionality is added--that the provided CycloneDX document is not JSON via an error message instead of reporting an invalid spec.

wdyt?

**Comment by cyberbliss** [comment]
Sounds like a good suggestion to me
