### ISSUE TITLE
spdx: follow LicenseRefs

### ISSUE THREAD

**Issue by justinabrahms** [eBay/sbom-scorecard#27]
Ref #22

**Comment by jspeed-meyers** [comment]
@justinabrahms, I can take a shot at this. Just LMK if you want me to.

**Comment by jspeed-meyers** [comment]
Of course, this task required more brainpower than I have on a Monday morning :)

I am trying to parse @rnjude's question:

> Does this tool count LicenseRefs as licenses in the license score or only SPDX License Identifiers?

I _think_ that this task involves determining if the current codebase counts both SPDX license identifiers (e.g. "MIT License" or, in the short form, "MIT") and also SPDX user defined license references as valid licenses.

To test this, I changed a couple of the licenses in the `julia.spdx.json` example from "MIT" to "LicenseRef-23". "LicenseRef-23" is a simple example of a SPDX user defined license references per official SPDX documentation: https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/

And good news: the tests still pass. This makes sense because the tool is simply checking (among other conditions) for a non-blank answer and this value satisfies that condition.

So the answer to:

> Does this tool count LicenseRefs as licenses in the license score or only SPDX License Identifiers?

is: **The tool counts both (at least currently).**

To ensure this functionality is preserved and changed only intentionally if need be, I've put in a PR that makes the tiny test case changes I described above.

LMK if you have questions. I think I need to go find some coffee.
